### ISSUE TITLE
Loop control flow is sometimes mistranslated

### ISSUE THREAD

**Issue by tchajed** [tchajed/goose#3]
GooseLang loop bodies produce a boolean indicating whether they should terminate or continue. Sometimes this boolean is incorrectly added to a loop body, particularly one that mixes `continue`, `break`, implicitly continuing, and `if` statements.

This is a major source of incorrect behavior in GooseLang, because the control flow that is handled is subtle and the mistranslated code mostly seems to work but has the wrong behavior. It would be better if we at least rejected complicated examples, and even better if they were handled properly.

**Comment by RalfJung** [comment]
It might be good to have some examples for things that are wrong, and how they should behave instead.

My own personal rule of thumb has been to not have any code paths that implicitly continue -- this has always fixed strange cases for me. Is that indeed a sufficient condition for correctness, or are there more edge cases?
