### ISSUE TITLE
Make it easier to run tests

### ISSUE THREAD

**Issue by RalfJung** [tchajed/goose#34]
Some tests are run by `go test`, but this is a lot less than what is actually run on CI. It'd be great if `go test` could somehow be made to test All The Things, or if that is not possible have `make test` or so that *does* test All The Things.

Currently, the most convenient way to run tests that I could find is to push to a branch and wait for CI to run...
(The README also doesn't say what to do.)

**Comment by tchajed** [comment]
`make ci` and `make fix` should cover everything in CI.

**Comment by RalfJung** [comment]
`make ci` terminates with
```
./test/bats/bin/bats ./test/goose.bats
make: ./test/bats/bin/bats: No such file or directory
```

**Comment by tchajed** [comment]
You just need `git submodule update --init --recursive`.
